<?php
/* Generated by neoan3-cli */

namespace Neoan3\Model;


use Neoan3\Apps\Transformer;

/**
 * Class TaskModel
 * @package Neoan3\Model
 * @method static find(array $array)
 * @method static create(array $array)
 * @method static update(array $array)
 */
class TaskModel extends IndexModel
{
    static function __callStatic($name, $arguments)
    {
        return Transformer::addMagic($name,$arguments);
    }

}
