<?php
/* Generated by neoan3-cli */

namespace Neoan3\Model;


use Neoan3\Apps\Db;

class TaskTransformer implements IndexTransformer
{
    static function modelStructure($givenId = false)
    {
        $mainId = $givenId ? $givenId : Db::uuid()->uuid;
        return [
            'id' => [
                'on_creation' => function($input,$all) use ($mainId){
                    $mainId = $input ? $input : $mainId;
                    return '$' . $mainId;
                }
            ],
            'is_done'=>[],
            'name' => [
                'required'=>true
            ],
            'prerequisites' => [
                'translate' => 'task_sub',
                'depth' => 'many',
                'on_creation' => [
                    'task_id' => function($input) use ($mainId){ return '$'.$mainId; }
                ]
            ],
        ];
    }
}
