<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Core\RouteException;
use Neoan3\Frame\Demo;
use Neoan3\Model\TaskModel;

class Task extends Demo
{
    function getTask(array $body)
    {

    }

    function postTask(array $body)
    {
        // TODO: secure
        try {
            $newTask = TaskModel::create($body);
        } catch (\Exception $e) {
            throw new RouteException($e->getMessage(), 400);
        }
        return $newTask;
    }

    function updateTask(array $body)
    {
        try{
            $updatedTask = TaskModel::update($body);
        }catch (\Exception $e) {
            throw new RouteException($e->getMessage(), 400);
        }
        return $updatedTask;
    }


}
